export const TASK_REQUEST = "TASK_REQUEST"

export const TASK_LIST_FAIL = "TASK_LIST_FAIL"
export const TASK_LIST_SUCCESS = "TASK_LIST_SUCCESS"

export const TASK_CREATE_FAIL = "TASK_CREATE_FAIL"
export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS"

export const TASK_UPDATE_FAIL = "TASK_UPDATE_FAIL"
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS"

export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL"
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS"
